services:
  app:
    build: .
    container_name: synergazing-app
    restart: unless-stopped
    ports:
      - "3002:3002"
    volumes:
      - ./storage:/root/storage
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - synergazing-net

  db:
    image: postgres:15-alpine
    container_name: synergazing-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: synergazing
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - synergazing-net

networks:
  synergazing-net:
    driver: bridge

volumes:
  postgres-data: