services:
  caddy:
    image: caddy:2-alpine
    container_name: synergazing-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - synergazing-net

  app:
    build: .
    container_name: synergazing-app
    restart: unless-stopped
    volumes:
      - ./storage:/root/storage
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - synergazing-net

  db:
    image: postgres:15-alpine
    container_name: synergazing-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: synergazing
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - synergazing-net

networks:
  synergazing-net:
    driver: bridge

volumes:
  postgres-data:
  caddy_data:
  caddy_config: